### ISSUE TITLE
Support write output to file

### ISSUE THREAD

**Issue by halink0803** [hrishikeshrt/google_drive_ocr#3]
It seems the package does not support write the output to file itself. It is great if the command line has an option to write the ocr result to output file like .txt or docs or any text extension.

Thank you

**Comment by hrishikeshrt** [comment]
The module does support specifying `output_path` name in `perform_ocr` function.

By default, it adds `.google.txt` to the image stem.
So, if your input file was `image.png`, an output `image.google.txt' will be created beside it.

The CLI does not support specifying custom path, because often more than one images are in play.
I am opening another issue (#4) to provide more control over the suffix etc through CLI.

**Comment by halink0803** [comment]
@hrishikeshrt Yes, thank you for explanation, I found it. I saw the output to stdout and thought there is no file created.
Nicely close this issue.
